# Generated by Django 3.0.3 on 2020-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_profile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('BY', 'Belarus'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('KZ', 'Kazakhstan')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sur_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
