# Generated by Django 3.0.3 on 2020-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200317_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prof_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
