# Generated by Django 3.0.3 on 2020-03-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200317_1806'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.RemoveField(
            model_name='wishitem',
            name='itemId',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='Item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='wishitem',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishedItems', to='shop.Profile'),
        ),
    ]
