# Generated by Django 3.0.3 on 2020-03-17 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200317_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishitem',
            old_name='Item',
            new_name='item',
        ),
    ]
