# Generated by Django 3.0.3 on 2020-03-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MA', 'MANAGER'), ('DE', 'DELIVER'), ('US', 'USER')], default='US', max_length=2, null=True, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='sizeandavailable',
            name='available',
            field=models.IntegerField(default=1, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='sizeandavailable',
            name='foot_size',
            field=models.IntegerField(choices=[(32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47')], null=True, verbose_name='size'),
        ),
    ]
